print("Segunda caracteristica agregada")
print("Segunda caracteristica agregada")
print("Segunda caracteristica agregada")
print("Segunda  editada y agregada")
print("Segunda caracteristica agregada")
